### ISSUE TITLE
Misc.

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#9]
- [x] Align 'Create O&P' logo to left (not centered)
- [x] Decrease typeface size of 'ECF is a non...' at footer and align left
- [x] Put 'copyright ECF 2017' on the same line as previous and align to the right (match font size)
- [x] Use blue ECF logo in footer 
- [x] Add JMK logo to partners section (see svg in email from Justine)

**Comment by kaitlynhova** [comment]
1. How do you want the logos? With adding the new JMK logo it changes the # of logos from odd to even.  Take a look on [staging](http://ecf-website-staging.herokuapp.com/)
2. What size of typeface?
3. Where is this on the website? Do you mean the Website copyright in the footer? I don't recommend having the copyright for the website on the same line as the EIN number because it looks like you founded the company in 2017.

**Comment by kaitlynhova** [comment]
Updates on [production](https://ecf-website.herokuapp.com)
